default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: imidsac
  password: <%= ENV["DATABASE_PASSWORD" ] %>

development:
  <<: *default
  database: osamgraph_development
  host: localhost

test:
  <<: *default
  database: osamgraph_test

staging:
  <<: *default
  database: osamgraph_staging

production:
  <<: *default
  database: osamgraph_production
